version: 2
jobs:
  install:
    working_directory: ~/project
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test: 
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm run test:production
  build_and_deploy: 
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm run build
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish
workflows:
  version: 2
  full_deploy:
    jobs:
      - install:
          filters: 
            tags:
              only: /.*/
      - test:
          requires:
            - install
          filters: 
            tags:
              only: /.*/
      - build_and_deploy:
          requires: 
            - test
          filters: 
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
        