version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npm run test:production
      - run: npm run build 
  deploy:
    steps: 
    - checkout
    - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
    - run: npm publish

workflows:
  version: 2
  install_and_build:
    jobs:
      - install
      - build