version: 2
jobs:
  install:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
  test: 
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm run test:production
  build: 
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm run build
  deploy:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps: 
    - checkout
    - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
    - run: npm publish

workflows:
  version: 2
  full_deploy:
    jobs:
      - install
      - test
      - build
      - deploy