version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npm run test:production
      - run: npm run build
  deploy:
    - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
    - deploy:
        filters: 
          tags:
            only: /v[0-9]+(\.[0-9]+)*/
        command: npm publish

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - deploy