version: 2
jobs:
  install:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test: 
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm run test:production
  build: 
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm run build
  deploy:
    docker:
      - image: circleci/node:8
    steps: 
    - checkout
    - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
    - run: npm publish

workflows:
  version: 2
  full_deploy:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires: 
            - test
          filters: 
            branches:
              ignore: /.*/
            tags: 
              only:
                /v[0-9]+(\.[0-9]+)*/
      - deploy:
          requires: 
            - build
          filters: 
            branches:
              ignore: /.*/
            tags: 
              only:
                /v[0-9]+(\.[0-9]+)*/
        